asteroid-team/asteroid

asteroid/engine/container.py
asteroid/filterbanks/analytic_free_fb.py
asteroid/filterbanks/enc_dec.py
asteroid/filterbanks/free_fb.py
asteroid/filterbanks/inputs_and_masks.py
asteroid/filterbanks/param_sinc_fb.py
asteroid/filterbanks/stft_fb.py
egs/wham/FilterbankDesign/conf.yml
egs/wham/FilterbankDesign/train.py

This is very much work in progress but solving the issues we are facing here will have good impact on the rest of the code for the future.
This starts to integrate masks and inputs of complex filterbanks
The main thing to work on now is `Container` IMO. We'd like to keep the serializing and loading methods while allowing more flexibility for the user for different use cases.

Complex masks and inputs integration

---

asteroid/masknn/blocks.py
asteroid/masknn/norms.py

Added the DPRNN architecture. In Luo's TAC Conv2D is used for mask net. I have only tested this version which instead is more similar to plain ConvTasNet. 
Had to include also a 2D LayerNorm layer. 
Probably there is a better way and the vanilla _LayerNorm can be made compatible with 2D inputs

dprnn first commit

---

README.md
asteroid/engine/container.py
asteroid/filterbanks/__init__.py
asteroid/filterbanks/analytic_free_fb.py
asteroid/filterbanks/enc_dec.py
asteroid/filterbanks/free_fb.py
asteroid/filterbanks/inputs_and_masks.py
asteroid/filterbanks/param_sinc_fb.py
asteroid/filterbanks/stft_fb.py
egs/wham/ConvTasNet/train.py
tests/engine/container_test.py
tests/filterbanks/stft_test.py

This PR brings many improvements : 
- The whole class system for building filterbanks has been re-thought to enable easier extensibility, in particular
- The class `Filterbank` should be the mother class of all filterbanks. It contains abstract methods and common parameters. 
- The class `Encoder` and `Decoder` can be created from `Filterbank` instances, given them an appropriate forward as well as post-processing and mask application methods in the `Encoder` case. 
- Both `Encoder` and `Decoder` class have a classmethod `pinv_of` which can receive a filterbank and make the class the pseudo-inverse of the input filterbank.
- `asteroid.filterbanks.make_enc_dec` automatically creates a encoder and decoder from a small set of arguments. 
- Several input post processing and masking strategies …

Refactoring filterbanks and more

---

asteroid/engine/solver.py

There is a bug 🐛 that prevents to resume training from a checkpoint. 
Might as well being useless this PR if we decide to move to either to `ignite` or `pytorch-lightning` as loading will be handled by those,
see [#14](https://github.com/mpariente/AsSteroid/issues/14#issue-527157100).

fixed loading bug

---

asteroid/masknn/__init__.py
asteroid/masknn/blocks.py

- Fixes shape mismatch from #8
- `DPRNN` is globally importable from `masknn` now.
- Change signature in `DPRNN` to have only two positional arguments (same as `TDConvNet`).
`DPRNN` can simply be called like this now
```python
import torch
from asteroid.masknn import DPRNN
in_channels, n_src = 128, 2
model = DPRNN(in_channels, n_src)
inp = torch.randn(1, 128, 500)
out = model(inp)
```

[src] DPRNN signature change

---

asteroid/filterbanks/stft_fb.py
tests/filterbanks/stft_test.py

- Fix some small errors in the STFT computation in `STFTFB` to enable perfect reconstruction with classic sqrt of hanning window in analysis and synthesis. 
- Add the possibilty to compute perfect resynthesis window from a given analysis window and the hop size (close to how `paderbox` handles it @). Compared to usual approaches (compute window square OLA on the whole signal length and divide by it), this doesn't require any additional computation at runtime because the synthesis window is fixed. 
- Unit tests for perfect reconstruction in several common window/kernel size/ stride choices.
STFT is now perfectly stable, let's use it ! :wink: 
For people using it (@sunits, @JorisCos, @popcornell), please rebase master (or merge) when this is merged.

Perfectly invertible STFT

---

asteroid/filterbanks/enc_dec.py
tests/filterbanks/filterbanks_test.py

Need feedback on output shapes @popcornell @sunits @JorisCos please !
This adds support to multichannel 1D convolutions and transposed convolutions. It's useful for multichannel or multi-source STFT and iSTFT in particular. 
We also add support for convolution of 1D and 2D signals. Previously only 3D signals of shape `(batch, 1, time)` were supported in `Encoder.forward`. No need for batch or empty channel dimension anymore (but this is still supported) !
```python
import torch
from asteroid.filterbanks import STFTFB, Encoder, Decoder
batch=3
encoder = Encoder(STFTFB(512, 512, 256))
decoder = Decoder(STFTFB(512, 512, 256))
inp = torch.randn(32000,)
stft = encoder(inp)  # (freq, conv_time)
out =  decoder(stft)  # (1, time)
inp = torch.randn(batch, 32000)
stft = encoder(inp)   # (batch, …
```

Add support for multichannel convolutions

---

asteroid/torch_utils.py
egs/dns_challenge/baseline/model.py
egs/wham/ConvTasNet/eval.py
egs/wham/ConvTasNet/model.py
egs/wham/DPRNN/eval.py
egs/wham/DPRNN/model.py
tests/utils/torch_utils_test.py

Models where not loaded correctly because of `strict=False` and keys mismatch, my bad. 
- Model loading from a trained `System` is now easy with `torch_utils.load_state_dict_in`. This tries loading the state_dict as is, if it fails, it removes the string subparts corresponding to the upper module. 
Please read the docs and the unit tests, this should be quite clear and if it's not, tell me. 
- Evaluation scripts are updated accordingly to load model correctly 
- load_best_model function got to model.py file in the recipes because it makes more sense IMO
- Also added a `are_models_equal` in torch_utils.py to check if two models have the same weights or not (also unit tested).

Fix evaluation bugs

---

asteroid/losses/multi_scale_spectral.py
tests/losses/loss_functions_test.py

Content
This adds multi-scale spectral loss as described in [1] in paragraph 4.2.1. The implementation is compatible with the PITLossWrapper module with 'wo_src ' mode.
Also adds 2 unit tests for this loss function 
TODO
Implement 'pairwise' and 'w_src' compatibility for PITLossWrapper module
References
[1] Jesse Engel and Lamtharn (Hanoi) Hantrakul and Chenjie Gu and
Adam Roberts
DDSP: Differentiable Digital Signal Processing
International Conference on Learning Representations
ICLR 2020, https://openreview.net/forum?id=B1x1ma4tDr

Add multi-scale spectral loss 

---

asteroid/filterbanks/inputs_and_masks.py
tests/filterbanks/inputs_and_masks_test.py

We are converging on the _complex-like_ representation, which is practical as real and imaginary parts are treated as channels. The shape is `(..., 2*F, ...)` with any number dimensions before the _complex_ dimension. The real and imaginary parts are concatenated on this `2*F` axis.
The main critic against this is that the axis has to be known in order to perform operations on it. On the countrary, `torchaudio` has a `(..., 2)` convention which doesn't have this flaw, but I guess, will require a lot more of reshaping to use it in training etc...
- `check_complex` : checks that the tensor is _complex-like_
- `to_numpy` : converts a  _complex-like_ torch tensor to numpy complex array
- `from_numpy` : converts a np complex array to a  _complex-like_ torch tensor.
- `angle` : returns the …

More complex support

---

asteroid/metrics.py
egs/dns_challenge/baseline/eval_on_synthetic.py
egs/wham/ConvTasNet/eval.py
egs/wham/DPRNN/eval.py
egs/whamr/TasNet/eval.py
setup.py
tests/metrics_test.py

The goal would be to "normalize" metrics logging on Asteroid. If the same format is shared accross datasets and recipes, it is easier. 
The function works for both single and multi-source mixtures/estimate. 
Reuse the function in the recipes, where it can be used.

Add `get_metrics` method in asteroid

---

asteroid/engine/system.py
requirements.txt
setup.py

Everyhting in the title. 
We loose between 2 and 3dB performance on DPRNN training with the new version of pytorch-lightning. 
We'll get back to 0.7.x when the problem is fixed. 
Opened an issue [here](https://github.com/PyTorchLightning/pytorch-lightning/issues/1136) to tell them.

Downgrade to pl0.6.0

---

tests/filterbanks/filterbanks_test.py
tests/filterbanks/transforms_test.py
tests/losses/loss_functions_test.py
tests/losses/pit_wrapper_test.py
tests/masknn/blocks_test.py
tests/metrics_test.py

Reduce some dimensions for input tensors, specially in the slowest tests (use `--durations=N` to see the slowest N tests).

Speedup testing time

---

.travis.yml
asteroid/metrics.py
requirements.txt
setup.py

Release 0.1.1 actually won't work on PyPI because of the dependency on `pb_bss` which is not on PyPI. 
I uploaded `pb_bss_eval`, the evaluation part of `pb_bss` which can be seen on (my fork)[https://github.com/mpariente/pb_bss].
Thanks to this, the next release should work now.

Use pb_bss_eval on PyPI now

---

asteroid/masknn/consistency.py
tests/masknn/consistency_test.py

Simple mixture consistency constraints that works for waveforms and spectrograms (and anything actually). 
If consistency weights are not specified, they are computed based on relative power so that silent sources do get residual as well. 
Corresponds to 3.2.2 of [this paper](https://arxiv.org/abs/1811.08521)

Added mixture consistency constraints

---

asteroid/losses/__init__.py
asteroid/losses/stoi.py
requirements.txt
setup.py
tests/losses/loss_functions_test.py

I finally implemented the STOI loss with some minor modifications. 
Implementation can be found [here](https://github.com/mpariente/pytorch_stoi).
I just wrapped the class in Asteroid and added an example to the docstring (we might want to insert it before the reference section, I'll see when I have time for that). 
Also, this is not yet suitable for non-PIT applications with a source axis because 
`(batch, n_src, dim2, time) --> (batch, n_src, dim2)`, we just need to take an average and I'll probably do it here rather than there.

Add support for STOI loss

---

asteroid/losses/pit_wrapper.py
tests/losses/pit_wrapper_test.py

Until now, pairwise losses were averaged over each permutation, then compared to find the best permutation. This averaging is what we call `perm_reduce`. 
This PR removes makes it possible to choose different `perm_reduce` than average (which stays the default).
The `perm_reduce` function can also receive arguments at runtime, we might need it so we made it possible. 
@popcornell Could you review please ?

[src] Generalize ! Implement pairwise losses reduce function

---

asteroid/filterbanks/__init__.py
asteroid/filterbanks/griffin_lim.py
tests/filterbanks/stft_test.py

Inspired by librosa. 
The main diff is, we expect the `Encoder` object which created the spectrogram (if you have a spec, you probably have the Encoder that created it, and the signature is much easier)
We might need the `nn.Module` version of this to handle device placement in a better way.

Implement GriffinLim

---

asteroid/masknn/blocks.py
tests/masknn/blocks_test.py

This adds the possibility to make the same architecture as the v1 of the ConvTasnet paper, without skip connections. 
In particular, @etzinis used this version, can you confirm?

No skip option to TDCN

---

asteroid/filterbanks/__init__.py
asteroid/filterbanks/griffin_lim.py
asteroid/masknn/consistency.py
tests/filterbanks/stft_test.py

To my knowledge this is the first open source PyTorch implementation (though it's not hard to code)
- We update the target mixture to be `ISTFT(STFT(mixture))` for two reason 
- Shapes will match with the estimated waveforms after ISTFT
- Also, if the ISTFT introduces some modulations (if the window is not well chosen etc..), the we take them into account in the consistency correction. 
- The consitency correction as based on relative power by default (as in `mixture_consistency`) but source weights can also be fed. 
**Anyone** is welcome to review PRs

Implement MISI

---

egs/librimix/ConvTasNet/eval.py
egs/librimix/ConvTasNet/train.py
egs/wham/ConvTasNet/eval.py
egs/wham/ConvTasNet/train.py
egs/wham/DPRNN/eval.py
egs/wham/DPRNN/train.py
egs/wham/DynamicMixing/eval.py
egs/wham/DynamicMixing/train.py
egs/wham/FilterbankDesign/train.py
egs/wham/TwoStep/eval.py
egs/wham/TwoStep/train.py
egs/whamr/TasNet/eval.py
egs/whamr/TasNet/train.py
egs/wsj0-mix/DeepClustering/eval.py

`mode` argument in `PITLossWrapper` Should be deprecated soon.

[egs] Replace mode by pit_from

---

asteroid/masknn/convolutional.py

This will help having `Filterbank` combined with `TDConvNet` in a single model call, marching towards pretraining models. 
I favored renaming this one as it is basically unused, every paper uses `conv_kernel_size` of 3.
Backward compatible, obviously

Deprecate kernel_size in favor of conv_kernel_size in TDConvNet

---

asteroid/data/__init__.py
asteroid/data/musdb18_dataset.py
egs/musdb18/OpenUnmix/test_dataloader.py
egs/musdb18/README.md

this PR adds the MUSDB18 dataset and dataloaders as well as a smoke test recipe that includes optimal parameters for training MUSDB18 models.
This dataset is a variant of the [FixedSourcesTrackFolderDataset](https://github.com/sigsep/open-unmix-pytorch/blob/master/data.py#L414) from the Open-Unmix repository.
* it was stripped down to the most basic use cases
* dataloading is limited to soundfile to not increase the number of dependencies on asteroid
This means the dataset is only compatible with MUSDB18HQ and not work with the stems version of MUSDB18. Documentation and scripts to convert MUSDB18 to wav will be added later.

First draft of MUSDB18 dataset

---

asteroid/models/base_models.py

Instead of having 
```yml
fb_conf:
...
masker_conf:
...
state_dict:
...
```
We move to
```yml
model_args:
...
state_dict:
...
``` 
This is less architecture specific.

[src] New convention for asteroid-models

---

asteroid/__init__.py
asteroid/models/base_models.py
egs/dns_challenge/baseline/model.py
hubconf.py
tests/engine/system_test.py

We can load models from `torch.hub` now :rocket: 
Pretrained weights will come soon enough.
Tagging #53.

[hub] Add hubconf.py

---

asteroid/engine/optimizers.py
requirements.txt
setup.py
tests/engine/optimizers_test.py

All optimizers available [here](https://github.com/jettify/pytorch-optimizer) are _getable_ with from string.
The logic stays the same as before and optimizer supported before are still the same. It just adds more supported optimizers to Asteroid.

[src & tests] Depend on torch_optimizer for optimizer

---

asteroid/losses/pit_wrapper.py

Warning since v0.1.0, removing the `mode` argument.

[src] Deprecate PITLossWrapper `mode` argument

---

.gitignore
asteroid/__init__.py
asteroid/data/wham_dataset.py
asteroid/models/README.md
asteroid/models/__init__.py
asteroid/models/base_models.py
asteroid/models/publisher.py
asteroid/models/zenodo.py
asteroid/scripts/asteroid_cli.py
egs/wham/ConvTasNet/eval.py
egs/wham/ConvTasNet/run.sh
egs/wham/ConvTasNet/train.py
setup.py
tests/models/publish_test.py

- We opened a asteroid-models community both [in Zenodo](https://zenodo.org/communities/asteroid-models) and [Zenodo's sandbox](https://sandbox.zenodo.org/communities/asteroid-models).
- New Zenodo interface (I prefered writing this instead of depending on yet another third party lib)
- New CLI `asteroid-upload` to upload pretrained models directly to the Zenodo community. 
- Tests & docs
- Same for other ConvTasNet recipes
- Same for DPRNN recipes
- Add other architectures in `asteroid.models`
- Handle the loading from Hub (should be easy).
- Licenses and infos on the other datasets.
The CLI is made with and `entry-point` in the setup.py so it is installed with pip and accessible everywhere.
[This record](https://sandbox.zenodo.org/record/578753#.Xs7leBZ8JC0) (in sandbox) is an example …

Publishing pretrained models !!

---

egs/dns_challenge/baseline/run.sh
egs/fuss/baseline/run.sh
egs/librimix/ConvTasNet/run.sh
egs/wham/ConvTasNet/run.sh
egs/wham/DPRNN/run.sh
egs/wham/DynamicMixing/run.sh
egs/wham/TwoStep/run.sh
egs/whamr/TasNet/run.sh
egs/wsj0-mix/DeepClustering/run.sh

We've had feedback and this is the most common usecase so far
`find . -iname run.sh -exec sed -E -i 's/id=.?$/id=\$CUDA_VISIBLE_DEVICES/g' {} +`

[egs] GPU `id` defaults to $CUDA_VISIBLE_DEVICES in all recipes

---

asteroid/data/dns_dataset.py
asteroid/data/librimix_dataset.py
asteroid/data/musdb18_dataset.py
asteroid/data/wham_dataset.py
asteroid/data/whamr_dataset.py
asteroid/data/wsj0_mix.py

I'm going to ask the owners of the License / creators of the dataset to approve the License infos, directly in the code. Sorry for pinging.
These license info will be used to automatically generate the Attribution statement in the license of pretrained models.

Add License info on all supported datasets

---

egs/dns_challenge/baseline/train.py
egs/librimix/ConvTasNet/train.py
egs/wham/ConvTasNet/train.py
egs/wham/DPRNN/train.py
egs/wham/DynamicMixing/train.py
egs/wham/FilterbankDesign/train.py
egs/wham/TwoStep/train.py
egs/whamr/TasNet/train.py

They are not used because --id controls that in run.sh. 
There is no point to specify it twice.
Maybe the line just above the Trainer definition could be removed as well, I'll have to test it.

[egs] Remove gpus args in all train.py. 

---

egs/kinect-wsj/DeepClustering/eval.py
egs/librimix/ConvTasNet/eval.py
egs/wham/ConvTasNet/eval.py
egs/wham/DPRNN/eval.py
egs/wham/DynamicMixing/eval.py
egs/wham/TwoStep/eval.py
egs/whamr/TasNet/eval.py
egs/wsj0-mix/DeepClustering/eval.py

Sources and estimates were completely squeezed before converting to numpy. 
In enhancement task, the sources have dimension (1, time) so that went to (time,) instead of staying (1, time)
Estimates have shape (batch, n_src, time), which is (1, 1, time) which should be squeeze to (1, time) instead of (time,) 
Closes #139

[egs] Fix wavfiles saving in eval.py for enh_single and enh_both task

---

egs/librimix/ConvTasNet/eval.py
egs/librimix/ConvTasNet/local/prepare_data.sh
egs/librimix/ConvTasNet/run.sh

Hello again,
This time with a cleaner commit history and your suggestions.
Regarding the normalization before writing to disk, anything that avoids significant amount of clipping is possible. Matching the peak value to that of the mixture as you suggested is one possibility, so is matching the energy of the target source but I am not sure if any of these really matters.
Cheers,
Mathieu

Fix librimix corrected

---

.gitignore

Fixes #149.
Wasn't really sure what was the best place in `.gitignore` for these lines

ignore exp dirs in recipe directories

---

asteroid/models/base_models.py
tests/models/models_test.py

From now on, this will be possible: 
```python
from asteroid import DPRNNTasNet
model = DPRNNTasNet('mpariente/DPRNNTasNet_WHAM!_sepclean')
model.separate('path_to your_file.wav')
```
And the estimates will be saved in `path_to_file_est%i.wav`.

[src & tests] Support filenames at the input of `separate`

---

asteroid/masknn/norms.py
tests/masknn/norms_test.py

Feature-wise global layer normalization as it is used in TCN++ in FUSS and firstly proposed in Universal Sound Separation. 
Normalization is applied over all frames for each channel.

Feat wise global layernorm

---

egs/dns_challenge/baseline/train.py
egs/kinect-wsj/DeepClustering/train.py
egs/librimix/ConvTasNet/train.py
egs/wham/ConvTasNet/train.py
egs/wham/DPRNN/train.py
egs/wham/DynamicMixing/train.py
egs/wham/TwoStep/train.py
egs/whamr/TasNet/train.py
egs/wsj0-mix/DeepClustering/train.py

EarlyStopping was broken in pl 0.6.0 and now that it works, we are stopping too early.
I saw this behavior for DPRNN several times etc.. 
Related issue: #177

[egs] EarlyStopping Patience to 30 instead of 10. 

---

asteroid/losses/stoi.py

I was trying STOI loss and realised after listening to some early examples that something is wrong with high frequencies.  Realised that I forgot to set the sample rate param for STOI loss.
This PR adds it to the docstring example.
I'd go as far and advocate for making `sample_rate` and *required* parameter that does not have a default – I would expect that almost everyone has to use resampling anyways because they're training in some other sample rate than 10kHz.

STOI loss example: Add sample rate

---

.pre-commit-config.yaml
CONTRIBUTING.md
requirements.txt

First steps towards adopting [`black`](https://github.com/psf/black) !
The idea is to gain time and energy :
- No need to think about code style when writing
- No need to worry about code style when reviewing (huge loss of time)
- Easier for new comers to open their PRs 
For now, we'll stick with 120 line length, but we'll probably move to 100 afterwards. 
Also need to add `flake8` but I don't know it much yet.
**Resources**
- [Django adopting black](https://github.com/django/deps/blob/master/accepted/0008-black.rst): see the end for the procedure we'll follow
- [Why prettier in JS](https://prettier.io/docs/en/why-prettier.html): good read.
- [Linus about line length](https://lkml.org/lkml/2020/5/29/1038).

[tests] Add precommit hook with black

---

.flake8

@jonashaag I guess you're familiar with Flake8, does this look reasonable? 
I plan to handle line-length with black rather than with flake because the `# fmt: off` is more practical if needed.

[CI] Add .flake8 configuration

---

asteroid/masknn/attention.py
asteroid/models/base_models.py
asteroid/models/conv_tasnet.py
asteroid/models/dprnn_tasnet.py
asteroid/models/dptnet.py
codecov.yml
tests/losses/loss_functions_test.py
tests/models/models_test.py

- Add tests on attention module 
- #200 introduced the `encoder_activation` argument to `BaseTasNet` which was not serialized, this PR fixes that. 
- filter warning in loss tests for readable outputs

[src & tests] Fix serialization issues introduced in previous PR

---

asteroid/masknn/__init__.py
asteroid/masknn/_local.py
asteroid/masknn/convolutional.py
asteroid/models/__init__.py
asteroid/models/sudormrf.py
tests/models/models_test.py

Split SuDORMRF architectures in encoder/masker/decoder instead of the current design where things are entangled and the separator network cannot be used on custom features. 
- More modular -> Separator networks can be used outside asteroid. 
- Fit in encoder/masker/decoder architecture -> Inherit from `BaseTasNet` -> pretrained models OK.
- Small blocks are stored in masknn/_local.py and are private. 
- Added support for "all" activation functions for the output mask.
- No support for custom number of output bins (renamed `out_chan` by `bn_chan` because it was the inner dimension of the Ublocks, but it suggested otherwise). Adding support for it would be quite easy, should I do it?  
@etzinis would like to review?

[src & tests] Split SuDORMRF architectures in encoder/masker/decoder

---

asteroid/__init__.py
asteroid/masknn/__init__.py
asteroid/masknn/recurrent.py
asteroid/models/__init__.py
asteroid/models/lstm_tasnet.py
tests/README.md
tests/models/models_test.py

The implementation is not absolutely faithful to the original article. 
- No per-segment L2 normalization/rescaling
- No skip connection in stacked LSTM
- GlobLN used as "bottleneck layer"
- Stride support. 
@popcornell does this sound reasonable to you? 
This is the implementation we used in the Asteroid paper on the WHAM and WHAMR dataset.

[src & tests] Add LSTMTasNet to serializable models 

---

.coveragerc
.github/workflows/test_asteroid_package.yml
tests/models/publish_test.py

Publishing tests requires an `ACCESS_TOKEN` for Zenodo's sandbox. 
This can be set as a secret in the repo, but forks won't have it, so it will be skipped in PRs. 
Also, because this test can fail often, or take too much time, we'd like to isolate it in a separate step to easily see if this is the one failing.

[tests & CI] Fix tests for publishing

---

.github/workflows/test_docs.yml

As said by few people, RTD alone can be nasty so we should also rely on gh-pages.

[docs] Deploy docs to github pages

---

asteroid/scripts/asteroid_cli.py
setup.py

The is a first iteration, it works, but it's not optimal and raises some flaws of the current code. 
```bash
asteroid-infer url_or_path --files filename
asteroid-cli 'mpariente/ConvTasNet_WHAM!_sepclean' --files tmp.wav
asteroid-cli 'mpariente/ConvTasNet_WHAM!_sepclean'  --files a_folder a_filename a_glob/**/*.wav
```
`files` can be a list of filenames, foldernames and globs, we'll handle it. In case of a folder, we check the supported file formats in the folder (recursively)
- Thanks to `BaseModel`, we can now load all the models, just given the model pack, which makes it very easy. 
- Based on  `separate`, not much new code here.
- The `--files` argument is cool because versatile.
- soundfile doesn't support all format. Should we have a backup strategy? Librosa supports more formats? 
- …

[cli] Add asteroid-infer CLI to enhance/separate from the command line

---

asteroid/models/conv_tasnet.py
asteroid/models/dprnn_tasnet.py

Bug introduced in #204 
Should solve #255 
The default activation function at the output of the encoder should be linear for ConvTasNet and DPRNN, as it was in the past. 
Models trained with other encoder activation since v0.3.2 will still load correctly because the `encoder_activation` key is in the models args from there.

[src] Restore linear activation as default in ConvTasNet and DPRNN

---

asteroid/models/publisher.py

It's a useful info to have. 
Next thing will be to plot the train/val loss in the zenodo card.

[hub] Add software version section in published models

---

.pre-commit-config.yaml
asteroid/__init__.py
asteroid/complex_nn.py
asteroid/filterbanks/transforms.py
asteroid/masknn/_dccrn_architectures.py
asteroid/masknn/_dcunet_architectures.py
asteroid/masknn/activations.py
asteroid/masknn/base.py
asteroid/masknn/convolutional.py
asteroid/masknn/norms.py
asteroid/masknn/recurrent.py
asteroid/models/__init__.py
asteroid/models/base_models.py
asteroid/models/dccrnet.py
asteroid/models/dcunet.py
asteroid/models/demask.py
asteroid/utils/__init__.py
asteroid/utils/generic_utils.py
tests/models/models_test.py
tests/utils/utils_test.py

This is a WIP implementation of [Phase-aware Single-stage Speech Denoising and Dereverberation with U-Net](https://arxiv.org/abs/2006.00687).
I also want to implement [DCCRN: Deep Complex Convolution Recurrent Network for Phase-Aware Speech Enhancement](https://arxiv.org/abs/2008.00264) soon.
I'd like to get feedback on
- Usage of PyTorch 1.7+ native complex128 dtype rather than Asteroid style complex type or torchaudio style complex type.
- Code structure, class names, code placing. Many things I wasn't sure where to place in the Asteroid codebase.
- Location of complex norms, activations, etc.
- Dealing with input shapes in `DCUMaskNet.forward`. Due to the encoder/decoder structure only specific T/F dimensions will work without padding or other workarounds.

DCUNet and DCCRNet

---

asteroid/engine/schedulers.py
asteroid/engine/system.py
tests/engine/scheduler_test.py

- `plot` can be useful for the lazy ones (me included)
- It was a bit undiscoverable till now. It's still pretty undiscoverable but at least we mention it in the docs.

[src&tests] Improve scheduler's docs + add plot method

---

asteroid/dsp/overlap_add.py

The previous loss function to reorder the chunks was weird, this should fix it. 
Which loss function would make the most sense? Currently it's kind of unnormalized correlation. 
Also, we probably need a better unit test for this. 
@groadabike, could you checkout this branch and check if the reordering works better in your case please? That'd be great

[src] Fix LambdaOverlapAdd

---

asteroid/filterbanks/__init__.py
asteroid/filterbanks/analytic_free_fb.py
asteroid/filterbanks/enc_dec.py
asteroid/filterbanks/free_fb.py
asteroid/filterbanks/multiphase_gammatone_fb.py
asteroid/filterbanks/param_sinc_fb.py
asteroid/filterbanks/stft_fb.py
asteroid/models/base_models.py

We need a way to know what is the sampling rate supported by a model. That's one attempt to do it. 
Should we enforce a `samle_rate` argument in the `BaseModel`? What would be the pros and cons? 
Is it the good place to put it in the `Filterbank` + `_EncDec`? An alternative is to place it in `BaseEncoderMaskerDecoder` (and all the child classes) but some filterbanks already have a `sample_rate` argument (param sinc and MPGT) and there would be some conflict on that. 
Any feedback is appreciated on that as it will impact pretrained models and automatic resampling in `asteroid-infer` CLI.
Linked issue #264

[src&tests] Add sample_rate in `BaseEncoderMaskerDecoder` 

---

egs/demask/train.py
egs/dns_challenge/baseline/train.py
egs/librimix/ConvTasNet/train.py
egs/wham/ConvTasNet/train.py
egs/wham/DPRNN/train.py
egs/wham/DPTNet/train.py
egs/wham/DynamicMixing/train.py
egs/whamr/TasNet/train.py

This always bothers me because it breaks things like `print(a, b)`.

Don't override print()

---

.github/workflows/rebase.yml
asteroid/filterbanks/__init__.py
asteroid/models/base_models.py
asteroid/models/dcunet.py
asteroid/models/demask.py
asteroid/scripts/asteroid_cli.py
asteroid/utils/hub_utils.py
setup.py
tests/models/models_test.py

This implements the loading of known models with known sample rate, and raises error when sample rate is not known. 
Also made a CLI to register sample rate to model (for the lazy ones). Is there a better name (more explicit) than `asteroid-cli register-samplerate`?
Refs: #274 #283 #284

Load models without sample_rate

---

asteroid/dsp/overlap_add.py
asteroid/losses/pit_wrapper.py
tests/losses/pit_wrapper_test.py

This is WIP, but I think we could merge it pretty fast. 
@popcornell, if we were to change the `PITLossWrapper`, what would you like in the output? Currently the `min_loss_idx` in `find_best_perm` is really not useful because you need to rebuild the permutations to get the indices. 
We might have a backward-breaking release with the Filterbank `filters` from #237, maybe we could change that as well because I know it was blocking you in the past. 
I'll comment in the code and I'd like your feedback

[src & tests] Add Hungarian matcher to solve the linear sum assignement in PITLossWrapper

---

asteroid/models/base_models.py
asteroid/utils/torch_utils.py
tests/jit/jit_torch_utils_test.py
tests/utils/torch_utils_test.py

The step of shaping `reconstructed` is taken out of the class and turned into a torch scriptable function.
Thing I don't really like: keeping around the non squeezed version of `wav` just for reshaping.
Errors I got when I tried to avoid this issue:
* If `_shape_reconstructed` takes a tensor and a target dimension, e.g. (tensor, wav_dim), `wav_dim` is frozen during tracing and becomes a constant in the traced model. In other words, inputs of shapes other than what was seen during tracing may have the wrong output dimension
* To force the execution of `wav_dim = wav.ndim` in the traced model, I tried to write a function that just returns the `ndim` attribute of a tensor which would have been called inside `forward`. Turns out that a function that returns an `int` cannot be scripted...
If …

Rewrite forward of BaseEncoderMaskerDecoder to be more readable

---

asteroid/models/base_models.py

Simplifies structure of `BaseEncoderMaskerDecoder.forward` although the hooks are still called in the `forward_*` and `apply_masks` methods.
I am not sure about the shapes given the docstrings when they are indicated, and when they are not, it's because I didn't know if there was supposed to be an expected shape x).

Simplify base encoder masker decoder

---

asteroid/filterbanks/stft_fb.py
asteroid/models/base_models.py
asteroid/models/demask.py
tests/filterbanks/stft_test.py
tests/jit/jit_models_test.py
tests/models/demask_test.py

Fixes #293 
Quick summary of the changes:
- [ | ] Backward compatibility tests for `DeMask`. The tests are commented at the moment while waiting for a solution to #294 
- [   ] Check that recipe still runs
:hankey: `preprocess_product_input` does not seem right, but I did not find a nicer way of making `DeMask` compatible with the forward of `BaseEncoderMaskerDecoder`. Any suggestion welcome :)!
:hankey: `DeMask` takes a `fb_type` argument while all the other model classes (and `make_enc_dec`) use a `fb_name` argument. Changing it could break backward compatibility though :/

Refactor demask

---

README.md

Hi,
the link to the Getting started notebook was broken and the link to the Overview notebook was missing.

[docs] Fix collab links in README

---

asteroid/complex_nn.py
asteroid/data/avspeech_dataset.py
asteroid/data/sms_wsj_dataset.py
asteroid/dsp/overlap_add.py
asteroid/losses/multi_scale_spectral.py
asteroid/losses/stoi.py
asteroid/masknn/attention.py

- Use relative imports everywhere. 
- Ignore `UserWarning` from torchaudio's import
For reference:
```
torchaudio/backend/utils.py:53: UserWarning: "sox" backend is being deprecated. 
The default backend will be changed to "sox_io" backend in 0.8.0 and "sox" backend will be removed in 0.9.0. 
Please migrate to "sox_io" backend. Please refer to https://github.com/pytorch/audio/issues/903 for the detail.
```

[src] Clean imports

---

asteroid/losses/__init__.py
asteroid/losses/mixit_wrapper.py
asteroid/losses/pit_wrapper.py
docs/source/package_reference/losses.rst
tests/losses/mixit_wrapper_test.py
tests/losses/pit_wrapper_test.py

Hi!
I implemented a mixture invariant training loss wrapper inspired by the paper "Unsupervised sound separation using mixtures of mixtures." arXiv preprint arXiv:2006.12701 (2020). 
Specifically, there are two new options for PITLossWrapper:
1. `mix_it`: Find the best partition of the estimated sources that gives the minimum loss for the MixIT training paradigm. Valid for any number of mixtures as soon as they contain the same number of sources.
2. `mix_it_gen`: Find the best partition of the estimated sources that gives the minimum loss for the MixIT training paradigm. Valid only for two mixtures, but those mixtures do not necessarily have to contain the same number of sources. It is allowed the case where one mixture is silent.

Mixture Invariant Training

---

asteroid/models/base_models.py
tests/models/models_test.py

Addresses #318
From what I understood, the main concern in passing `sample_rate` to `BaseModel` is that we duplicate reference to it, and users might change it without changing other part of the model that reference it. See [comment](https://github.com/mpariente/asteroid/issues/318#issuecomment-723481927). 
This is what I propose: 
Having `__sample_rate` with dunder means that `model.__sample_rate` cannot be accessed/changed directly. But it can be accessed from `model._BaseModel__sample_rate` which most users won't even know IMO. 
Instead, we provide a setter for the `sample_rate` property and warn the user that there might be some inconsistencies. 
WDYT? 
```python
In [1]: class Trial:
...:     def __init__(self, sample_rate):
...:         self.__sample_rate = sample_rate
...: 
...: …
```

BaseModel takes sample_rate argument

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/how-to-question.md
asteroid/scripts/asteroid_versions.py
setup.py
tests/test_cli.py

We could use this as for the issue templates.
```
$ asteroid-versions
Asteroid            0.4.0rc0, Git checkout f7938f3413bb (asteroid-env)
PyTorch             1.7.0+cpu
PyTorch-Lightning   0.9.0
```

Add asteroid-versions script to print installed versions

---

asteroid/masknn/convolutional.py

Deprecate kernel_size in TDConvNet

---

asteroid/utils/hub_utils.py
setup.py
tests/models/models_test.py
tests/utils/hub_utils_test.py

In this Pull request:
- The few important code changes (not too many lines) are in `cached_download()`, and in `hf_bucket_url()` to support falling back to the huggingface.co model hub if we don't know what to do with the method param.
-  The rest of the additions are copy/pasted from transformers and are not strictly speaking required, but should work well and cover a few additional edge cases compared to your current file downloading/caching code.
If it's too much code, feel free to remove/update some of it. We could also spin this code off into a utility library (`pip install huggingface_hub`?) at some point.
The unit tests mostly check that we can resolve model ids to local paths, and adds an example test that loads a model from a hf model id (I had to update the model to include a …

[hub_utils] Support for huggingface model hub

---

asteroid/utils/hub_utils.py

Just so that we can do that. 
```python
In [6]: from asteroid.utils.hub_utils import model_list
In [7]: model_list(name_only=True)
Out[7]: 
['julien-c/DPRNNTasNet-ks16_WHAM_sepclean',
'mpariente/ConvTasNet_WHAM_sepclean']
```
We'll exchange it with the current `show_available_models` etc.. when we get rid of Zenodo.

List asteroid models in HF's hub

---

asteroid/masknn/attention.py

see https://github.com/asteroid-team/asteroid/issues/380

hopefully fixes DPTNet this time 

---

asteroid/engine/system.py

The base implementation now throws a warning, see https://github.com/PyTorchLightning/pytorch-lightning/blob/81fd33b431578129de6ea19b99af7da87b1081bf/pytorch_lightning/core/lightning.py#L502

Remove call to super().training_step()

---

asteroid/data/librimix_dataset.py
asteroid/metrics.py
egs/librimix/ConvTasNet/eval.py
egs/librimix/ConvTasNet/local/get_text.py
egs/librimix/ConvTasNet/local/prepare_data.sh
egs/librimix/ConvTasNet/run.sh

So that's a first iteration for ASR evaluation in the LibriMix recipe. 
Thanks to @JorisCos  for some of the ground work. 
I'll comment in the PR about things I'm unsure about and where I'd like help hopefully.
None of the code has been ran yet, things will likely change place but this is just a rough draft to see how easy it would be to do it. 
@raikarsagar @JorisCos @popcornell @mhu-coder

ESPNet integration: v0

---

asteroid/models/dccrnet.py
asteroid/models/dcunet.py
tests/jit/jit_models_test.py
tests/models/models_test.py

This PR adds `stft_n_filters` as mentionned in #404.
It also fixes the defaults parameter of DCUNet to match its paper as mentionned in #400

Add stft_n_filters to BaseDCUNet

---

asteroid/metrics.py

- This PR  makes it possible to keep track of the transcriptions made by the ASR models.
The file containing the transcriptions is a `.json` that looks like this :
- This PR also adds jiwer transformation to the measure computation. It removes the punctuation and puts everything to lowercase. This leads to a more accurate WER.

Wer tracker

---

asteroid/engine/system.py

Add note about System Lightning hooks

---

egs/kinect-wsj/DeepClustering/train.py
egs/wsj0-mix/DeepClustering/train.py

Makes `wsj0-mix/DeepClustering` final save like `wham/DPTNet`.
[PyTorch Lightning's `pytorch_lightning.callbacks.ModelCheckpoint`](https://pytorch-lightning.readthedocs.io/en/stable/generated/pytorch_lightning.callbacks.ModelCheckpoint.html) assumes `dirpath + filename` not a `dirpath` as its first argument, but line 83 assumes a `checkpoints` folder exists.
So when this example runs this error occurs:
```
Epoch 132: 100%|█████████▉| 666/667 [04:11<00:00,  2.65it/s, Epoch 132, step 70888: val_loss was not in top 5
Epoch 132: 100%|██████████| 667/667 [04:11<00:00,  2.65it/s, loss=2.07e+03, v_num=0]
Traceback (most recent call last):
File "train.py", line 202, in <module>
main(arg_dic)
File "train.py", line 83, in main
torch.save(system.model.state_dict(), os.path.join(exp_dir, …
```

#Minor Fixes final checkpoint save for wsj0-mix DeepClustering example.

---

asteroid/dsp/overlap_add.py
asteroid/models/base_models.py
asteroid/separate.py
tests/models/models_test.py

Started implementing what I suggested in #420. 
I'll highlight the places where I doubt in the PR. 
Funny things I found along the way: 
- It's hard to make a model that doesn't take the sample rate as argument 
```python
class Model(BaseModel):
def __init__(self):
super().__init__(sample_rate=44100)
def forward(self, x):
return x
def get_model_args(self):
return {}
```
This can be serialized, but not loaded because `sample_rate` is needed in the model conf to load the model. 
OTOH:
```python
class Model(BaseModel):
def __init__(self):
super().__init__(sample_rate=44100)
def forward(self, x):
return x
def get_model_args(self):
return {"sample_rate": self.sample_rate}
```
This fails at loading, because it tries to pass `sample_rate` as kwargs, but cannot. 
Should we do something about …

[src] Multichannel models 

---

asteroid/models/base_models.py
tests/models/models_test.py

As discussed in #427, we'll remove default sample rate argument. 
We start with a deprecation warning when it is not passed, and will remove it in a later release.

[src] Make sample rate positional

---

asteroid/models/lstm_tasnet.py
asteroid/models/sudormrf.py
tests/models/models_test.py

Important fix ! 
Because the encoder was wrapped in `LSTMTasNet` and `SudoRmRF*`, `getattr` couldn't find it and it was not passed to `BaseModel`. 
Funny that we set barriers to load models without sampling rate, but managed to load models with the wrong sampling rate..  :sweat_smile:

[src] Fix unpassed SR in TasNet and SudoRMRF

---

asteroid/dsp/overlap_add.py
asteroid/models/base_models.py
asteroid/separate.py
tests/models/models_test.py

This was pointed out by @jonashaag as a potential name. 
I was against using `out_channels` instead of `n_src` and ruled out `in_channels` in the same time. Got back to it, I think `in_channels` makes more sense and is more consistent with PyTorch's code, so it's better.

[src] Change n_channels to in_channels

---

asteroid/utils/hub_utils.py
requirements/torchhub.txt
setup.py
tests/utils/hub_utils_test.py

Refs #401
Switch to huggingface_hub and allow for https://huggingface.co/ prefixed URLs. 
We can also merge without the URL change if @julien-c doesn't like it.
CI currently fails due to missing dependency bump

Use huggingface_hub dependency, remove inlined HF code

---

docs/source/conf.py

Hopefully this shuld fix it. 
This is black magic for me so we'll see.

[docs] Fix wrong links in docs

---

asteroid/dsp/beamforming.py
docs/source/package_reference/dsp.rst
tests/dsp/beamforming_test.py

This is inspired by the code in [`nn-gev`](https://github.com/fgnt/nn-gev/blob/f8287020b18a00dd34eb58ba439b8d7dfad74fac/fgnt/beamforming.py) from Paderborn and François Grondin's code in [speechbrain](https://github.com/speechbrain/speechbrain/blob/develop/speechbrain/processing/decomposition.py).
Thanks for open-sourcing it. 
Also helped by @popcornell for MWF
- GCCPhat with quadratic interpolation (cf François Grondin's code)
- steering vector 
- Blind analytic normalization 
- GEV vector phase correction
- More docs
- Examples
- Tests
Might be interesting for @boeddeker @FrancoisGrondin @faroit

Add beamforming modules

---

requirements/install.txt
requirements/torchhub.txt

The asteroid-filterbanks 0.4.0 release is the first with torch>=1.8.0 support only, start from there.

Drop support for torch<1.8.0

---

.pre-commit-config.yaml
asteroid/dsp/beamforming.py
tests/dsp/beamforming_test.py

As @popcornell  pointed out, numpy automatically casts to double for solving, and torch doesn't. 
This PR makes sure that all the solve, cholesky and inverse ops are done in double (float or complex).

[src] Compute linalg beamforming ops in double

---

asteroid/dsp/__init__.py
asteroid/dsp/beamforming.py
tests/dsp/beamforming_test.py

We had a small vote on the slack channel and all caps for abbreviations in class names are more unanimous. 
Also change atf to rtf in function names because it's closer to reality.
And add placeholder code for @popcornell `SoudenMVDRBeamformer`.

Improve Beamforming naming and add TODOs

---

asteroid/dsp/beamforming.py

Add a global flag and two functions to switch between float and double linalg ops.
An unchangeable default is a bad idea!

[src] Enable forcing float for linalg ops

---

docs/source/readmes/pretrained_models.md
model_card_template.md
model_cards/README.md
model_cards/by_username/Cosentino/ConvTasNet_LibriMix_sepclean.md
model_cards/by_username/Cosentino/ConvTasNet_LibriMix_sepnoisy.md
model_cards/by_username/groadabike/ConvTasNet_DAMP-VSEP_enhboth.md
model_cards/by_username/mpariente/ConvTasNet_WHAM_sepclean.md
model_cards/by_username/mpariente/DPRNNTasNet(ks=16)_WHAM_sepclean.md
model_cards/by_username/mpariente/DPRNNTasNet_WHAM_sepclean.md

I also added the models from Brij and Tucker who couldn't do it. 
Now, all models from Zenodo are on Hugging Face's Model Hub. 
We should remove all the code for it, it will come in its own time.

[docs] Update instructions for pretrained model sharing

---

asteroid/models/__init__.py
asteroid/models/x_umx.py
asteroid/utils/hub_utils.py
egs/musdb18/X-UMX/README.md
egs/musdb18/X-UMX/eval.py
egs/musdb18/X-UMX/local/conf.yml
egs/musdb18/X-UMX/local/dataloader.py
egs/musdb18/X-UMX/requirements.txt
egs/musdb18/X-UMX/run.sh
egs/musdb18/X-UMX/train.py
egs/musdb18/X-UMX/utils
tests/models/xumx_test.py

Thank @TE-StefanUhlich, @faroit and @mpariente for lots of efforts!! I would like to do PR regarding X-UMX. 
The differences between `official master` and `xumx_branch` are summarized as follows:
[newly added]
･`asteroid/tests/models/xumx_test.py`
･`asteroid/egs/musdb18/X-UMX`
･`asteroid/asteroid/models/x_umx.py`
[modified]
･`asteroid/asteroid/models/__init__.py`
･`asteroid/asteroid/utils/hub_utils.py`

Recipe for X-UMX (using MUSDB18)

---

requirements/install.txt
setup.py

The tests are failing for now so something is broken. 
We'll have to do a release for lightning<1.3.0, and fix what's broken and upgrade. 
Indentified in #492

[instal] Bump lightning version under 1.3.0

---

setup.py

[install] Drop support for torch<1.8

---

asteroid/models/conv_tasnet.py

This is to avoid using any non causal  `norm_type` when `causal=True`.

Fix default norm_type for causal ConvTasNet

---

asteroid/models/conv_tasnet.py

Using `cLN` gives significant better results than `cgLN` it should be used as default.

Default norm in causal convTasnet 

---

notebooks/01_APIOverview.ipynb
notebooks/README.md

``asteroid.filterbanks`` to ``asteroid_filterbanks``
This PR is with the issue "No module named 'asteroid.filterbanks' #525"

``asteroid.filterbanks`` to ``asteroid_filterbanks``

---

asteroid/metrics.py
egs/librimix/ConvTasNet/eval.py

In eval.py line 74, pass ```conf["use_gpu"]``` to ```WERTracker```.
In metrics.py line 231 add ```self.device = 'cuda' if use_gpu else 'cpu'``` and pass ```device=self.device``` to ```Speech2Text```.

eval wer with gpu

---

requirements/install.txt
setup.py

This should fix unit tests and not be backward incompatible. 
The next step could either be: 
1) Drop support for PL<1.3.0  
2) Check PL versions
I'd vote for the first one.

[install] Fix PL version <1.5.0

---

asteroid/losses/mixit_wrapper.py
egs/wham/MixIT/train.py
tests/losses/mixit_wrapper_test.py

This solves the issue #594 and adds a simple dimension check to prevent using wrong loss function with MixIT wrapper.

MixIT loss function

---

asteroid/losses/cluster.py

This solves the documentation issue #591 
In the example, the arguments where being passed as a list while the function expected three separate arguments, as explained on the comments of the issue.

Fix documentation deep_clustering_loss example

---

asteroid/dsp/beamforming.py

According to https://github.com/pytorch/pytorch/issues/72721 complex32
will be brought back in a later version, this constraint should be
removed then.
This addresses issue https://github.com/asteroid-team/asteroid/issues/608.

[install] torch.complex32 has been removed from 1.11.0

---

asteroid/masknn/convolutional.py

As the length of input audio tensor, sometimes U-ConvBlock's tensor shape becomes odd number.
In this case, shape miss-matching is occurred in process of downsampling and upsampling.
This commit trims additional last data in upsampling sequence.

Fix shape mismatching in SuDORMRF's masknn

---

requirements/docs.txt

Jinja problem from [here](https://github.com/sphinx-doc/sphinx/issues/10291)
This should fix docs build

Restrict jinja2>=3.0.0,<3.1.0

---

asteroid/engine/schedulers.py
asteroid/engine/system.py
requirements/install.txt
setup.py
tests/losses/sinkpit_wrapper_test.py

- Remove the deprecated `output` parameter from `on_train_epoch_end`
- Add a simple custom `lr_scheduler_step` to the base model
- Remove the PL upper version constraint
This allows also torchmetrics to follow PL, which caused problems when PL was pinned and not torchmetrics.

Raise PL requirement to 1.3.0

---

asteroid/utils/hub_utils.py

Fix #644 
Removes the warning by following the upgrade instructions

Upgrade deprecated huggingface_hub.cached_download

---

README.md
egs/wsj0-mix-var/Multi-Decoder-DPRNN/.vscode/settings.json
egs/wsj0-mix-var/Multi-Decoder-DPRNN/README.md
egs/wsj0-mix-var/Multi-Decoder-DPRNN/eval.py
egs/wsj0-mix-var/Multi-Decoder-DPRNN/model.py
egs/wsj0-mix-var/Multi-Decoder-DPRNN/requirements.txt
egs/wsj0-mix-var/Multi-Decoder-DPRNN/run.sh

Also refactoring my demo website and all that, make it easier to use

Update Multi-Decoder DPRNN with inference function on a single file out-of-the-box

---

asteroid/dsp/overlap_add.py

allows to use LambdaOverlapAdd also on GPU without calling before .to on the instantiated module.

Update overlap_add.py, auto casting device for window

---

asteroid/dsp/beamforming.py
asteroid/engine/schedulers.py
asteroid/engine/system.py
asteroid/models/x_umx.py
notebooks/03_PITLossWrapper.ipynb
requirements/install.txt
requirements/torchhub.txt
setup.py
tests/complex_nn_test.py
tests/dsp/consistency_test.py
tests/dsp/overlap_add_test.py
tests/jit/jit_filterbanks_test.py
tests/jit/jit_masknn_test.py
tests/jit/jit_models_test.py
tests/losses/loss_functions_test.py
tests/losses/pit_wrapper_test.py
tests/losses/sinkpit_wrapper_test.py
tests/masknn/activations_test.py
tests/models/demask_test.py
tests/models/models_test.py
tests/models/xumx_test.py
tests/utils/utils_test.py

This PR finally upgrades the dependencies and fixes the issues related to it. In particular :
- Remove the `optimizer_idx` in `lr_scheduler_step` in `System`.
- Replace `torch.symeigh` by `torch.linalg.eigh` in beamforming.py
- Disable X-UMX as it uses torch1.x STFT : @r-sawata do you want to fix it ? 
- Replace `on_*_end` with `on_training_*_end`
- Replace `torch.testing.assert_allclose` with `torch.testing.assert_close`.

Upgrade dependencies to torch 2.x and lightning 2.x

---

asteroid/dsp/overlap_add.py

Hey there,
`_reorder_sources()` is called with the *current* and the *previous* frames as arguments. The way it had been coded, the previous frame might have been scaled or windowed already. But to get best results, we probably want to compare to an unscaled, un-windowed version. That's what this change fixes.
Cheers.

_reorder_sources() in OLA compares scaled/windowed frame with un-scaled/un-windowed frame

---

asteroid/models/x_umx.py

Hello!
I know we should ideally rewrite the XUMX model to work with the new torch's complex type, but it is possible to workaround this by just converting the new type to the old format just after calling `torch.stft` using `torch.view_as_real` and then converting it back to the new type with `torch.view_as_complex` before calling to `torch.istft` (#662) .  This is not the ideal solution but I think it would be useful to allow people to keep using XUMX till the model is fully rewrited.
Best,
David

Quick fix for XUMX in torch 2.0

---

asteroid/dsp/beamforming.py

Seems like there was a missing `super().__init__()` in the GEV-D beamformer class definition, causing improper inheritance of attributes from the parent `Beamformer` class. 
Notably, this is not the case for the SDW-WMF beamformer class definition.
Caused an error when calling a beamformer instance.
```
>>> import asteroid.dsp.beamforming as bf
>>> beamformer = bf.GEVDBeamformer()
>>> stft_enhanced = beamformer(mix=signal_noisy, target_scm=psd_clean, noise_scm=psd_noise)
AttributeError: 'GEVDBeamformer' object has no attribute '_backward_hooks'
```

Fix a missing super-init in the GEVD beamformer class

---

asteroid/masknn/tac.py

An example of the SyntaxWarning messages I was getting:
```
/usr/local/lib/python3.12/site-packages/asteroid/masknn/tac.py:15: SyntaxWarning: invalid escape sequence '\_'
.. note:: Supports inputs of shape :math:`(batch, mic\_channels, features, chunk\_size, n\_chunks)`
/usr/local/lib/python3.12/site-packages/asteroid/masknn/tac.py:42: SyntaxWarning: invalid escape sequence '\_'
Shape: :math:`(batch, mic\_channels, features, chunk\_size, n\_chunks)`.
```

Make a docstring a raw-string to avoid a syntax warning
