asteroid/engine/solver.py, asteroid/utils.py, egs/wham/ConvTasNet/conf.yml, egs/wham/ConvTasNet/train.py
Refactor `Solver` to enable easy overwriting of sub-methods and give more freedom to the user.
=> Refactor Solver class and rewrite ConvTasNet/train.py accordingly

asteroid/engine/optimizers.py, asteroid/filterbanks/__init__.py, asteroid/masknn/activations.py, asteroid/masknn/blocks.py, egs/wham/ConvTasNet/conf.yml, egs/wham/ConvTasNet/train.py
As in `norms.py`, the `get` function is implemented for activation functions, optimizers and filterbanks. 
This makes it easier to loop over them from the command line without having several if statements in the main python file. 
Also, the previous behaviour (importing and instantiating the classes) still work perfectly fine.
Corresponding issue: #4
=> Getting classes from their names

egs/sms_wsj/CaCGMM/README.md, egs/sms_wsj/CaCGMM/conf.yml, egs/sms_wsj/CaCGMM/local/prepare_data.sh, egs/sms_wsj/CaCGMM/local/start_evaluation.py, egs/sms_wsj/CaCGMM/run.sh, egs/sms_wsj/CaCGMM/utils/parse_options.sh, egs/sms_wsj/CaCGMM/utils/prepare_python_env.sh
This is an CaCGMM based baseline system for sms_wsj as presented in 
https://arxiv.org/abs/1910.13934
It mostly relies on code from https://github.com/fgnt/sms_wsj and https://github.com/fgnt/pb_bss
=> initial commit for mm based sms_wsj example

asteroid/engine/system.py, asteroid/losses/__init__.py, asteroid/losses/mse.py, asteroid/losses/pit_wrapper.py, asteroid/losses/si_sdr.py, egs/wham/ConvTasNet/train.py, egs/wham/FilterbankDesign/train.py, tests/losses/mse_test.py, tests/losses/pit_wrapper_test.py, tests/losses/si_sdr_test.py
I'll take more time to describe what it does soon but this is ready for merging. 
Anyone wanting to review it is welcome !
Cheers !
=> New API for PIT and non PIT losses 

.coveragerc, .travis.yml, README.md, asteroid/__init__.py, asteroid/engine/optimizers.py, asteroid/engine/system.py, asteroid/filterbanks/__init__.py, asteroid/filterbanks/enc_dec.py, asteroid/filterbanks/inputs_and_masks.py, asteroid/filterbanks/stft_fb.py, asteroid/masknn/activations.py, asteroid/masknn/blocks.py, asteroid/masknn/norms.py, asteroid/utils.py, tests/README.md, tests/engine/optimizers_test.py, tests/engine/system_test.py, tests/filterbanks/filterbanks_test.py, tests/filterbanks/inputs_and_masks_test.py, tests/filterbanks/stft_test.py, tests/masknn/activations_test.py, tests/masknn/blocks_test.py, tests/masknn/norms_test.py, tests/utils/utils_test.py
Extend coverage and improve existing unit tests.
- Fix bug in `TDConvNet` ([commit](https://github.com/mpariente/AsSteroid/commit/4bfe61d80bee8960a9cc018f9dcfa5d70c4133c0))
- Fix bug in `DPRNN`, use `out_chan` at the output layer (enable different input and output size for magnitude masks for example)
- Fix `CumLN` : use parent class method.
- `optimizers.get` now works
- Window needs to be of size `kernel_size` in `STFTFB`.
- Use `nn.Identity()` for linear activation.
- Add build badge
- Add README for running tests
- Add .coveragerc (omit data directory for now)
_Please do not merge when review is done_ :smile:
=> Improve tests and coverage + bug fixes

README.md, requirements.txt
Add a note on README for better install.
=> Fix install warnings

.coveragerc, asteroid/engine/system.py, asteroid/utils.py, codecov.yml, egs/wham/ConvTasNet/conf.yml, egs/wham/ConvTasNet/eval.py, egs/wham/ConvTasNet/run.sh, egs/wham/ConvTasNet/train.py, egs/wham/FilterbankDesign/conf.yml, requirements.txt, tests/utils/utils_test.py
Mainly, the `eval.py` script was missing and the `run.sh` was incomplete so this fixes that. 
The Convtasnet recipe should run seamlessly from any stage. 
I'm still not satisfied with the way python is handled in the recipe (`python_path` env variable). Any suggestion is welcome.
Anyone is free to review the PR, I'll leave it open a small while.
=> ConvTasnet recipe ready

egs/wham/ConvTasNet/utils/prepare_python_env.sh, egs/wham/DPRNN/conf.yml, egs/wham/DPRNN/eval.py, egs/wham/DPRNN/local/convert_sphere2wav.sh, egs/wham/DPRNN/local/prepare_data.sh, egs/wham/DPRNN/local/preprocess_wham.py, egs/wham/DPRNN/model.py, egs/wham/DPRNN/run.sh, egs/wham/DPRNN/train.py, egs/wham/DPRNN/utils/parse_options.sh, egs/wham/DPRNN/utils/prepare_python_env.sh
Added recipe for DPRNN (adapted the Conv-TasNet one). 
Also added relative path for env installation of requirements. 
The env setup still fails because of pb-bss but we already knew that.
=> DPRNN recipe

asteroid/torch_utils.py, egs/dns_challenge/README.md, egs/dns_challenge/baseline/denoise.py, egs/dns_challenge/baseline/eval_on_synthetic.py, egs/dns_challenge/baseline/local/preprocess_dns.py, egs/dns_challenge/baseline/model.py, egs/dns_challenge/baseline/run.sh, tests/utils/torch_utils_test.py
This PR adds evaluation scripts and denoising scripts to the baseline recipe. 
There are still a few TODOs, especially things that could be more general and that got here first just by convenience. 
Also `preprocess_dns.py` should be modified to follow [this](https://github.com/mpariente/asteroid/compare/dns_eval?expand=1#diff-54fd0e82eb83ad730e6508404a61a0c4R78) preprocessing which is 3x faster.
=> Evaluation for the DNS Challenge

asteroid/losses/pit_wrapper.py
Small fix Pit_wrapper to allow parallel computing for all loss functions
=> Small fix for parallel GPU usage

asteroid/masknn/norms.py, tests/masknn/norms_test.py
as the title... felt we should add this in order to have existing blocks support batchnorm.
=> added aliases for Pytorch BatchNorm1D and 2D

.travis.yml, docs/requirements.txt, docs/source/conf.py
Using caching, could gain 1min40s in the build. 
I expected to gain more. 
This might not be worth it so keep it mind.
=> Speedup the travis build with caching

docs/requirements.txt, docs/source/conf.py
Just pin sphinx version under 3.0 for now. 
We'll see later
=> Fix build erros 

egs/wham/ConvTasNet/run.sh, egs/wham/ConvTasNet/train.py
I fixed two bugs.
1. asteroid\egs\wham\ConvTasNet\run.sh
the mode variable was being overwritten
2. asteroid\egs\wham\ConvTasNet\train.py
the max_nb_epochs tag was deprecated
=> Fixed two bugs in ConvTasNet

asteroid/filterbanks/enc_dec.py
- Add support for `padding` in `Encoder`
- Add support for `padding` and `output_padding` in  `Decoder`
- Improve the docs a bit
=> Improve Encoder and Decoder classes

egs/wham/TwoStep/run.sh, egs/wham/TwoStep/system.py, egs/wham/TwoStep/train.py
Mainly avoid the crash due to filterbank not found on first run. 
Also, make experiment tagging possible again. 
@etzinis I'll wait for your approval, as this is your code!
=> Twostep fix

asteroid/masknn/blocks.py, egs/wham/DPRNN/README.md, egs/wham/DPRNN/local/conf.yml, egs/wham/DPRNN/run.sh, egs/wham/DPRNN/train.py
- Update architecture to have masking in both 3D and 2D domains, the gating after fold and relu as final activation
- Retrain ks=16 and ks=2 models. 
Finally, we can reproduce the results (actually better) from the paper.
=> DPRNN again (+results)

asteroid/data/wav.py, asteroid/data/wsj0_mix.py, asteroid/filterbanks/transforms.py, asteroid/losses/cluster.py, asteroid/masknn/blocks.py, egs/wsj0-mix/DeepClustering/eval.py, egs/wsj0-mix/DeepClustering/local/conf.yml, egs/wsj0-mix/DeepClustering/local/preprocess_wsj0mix.py, egs/wsj0-mix/DeepClustering/model.py, egs/wsj0-mix/DeepClustering/run.sh, egs/wsj0-mix/DeepClustering/simple_train.py, egs/wsj0-mix/DeepClustering/train.py, egs/wsj0-mix/DeepClustering/utils, egs/wsj0-mix/DeepClustering/wsj0_mix_dataset.py, egs/wsj0-mix/create_meta_files.py, tests/filterbanks/transforms_test.py, tests/losses/loss_functions_test.py
- Energy-based VAD which correctly computes VAD independently on batch dim (and any leading dimension)
- Normalize final cost based on VAD mask, independently on batch_dim
- Improve docs in `deep_clustering_loss`. 
- Start run.sh with steps and parameters
- Use WHAM-like wsj0-mix preprocessing
- Use WHAM-like data.Dataset (recipe-local for now) 
I'll push the changes to the training and eval script when I have final results, and make another PR for those.
=> Source changes towards deep clustering recipe

egs/dns_challenge/baseline/run.sh, egs/fuss/baseline/run.sh, egs/librimix/ConvTasNet/run.sh, egs/sms_wsj/CaCGMM/local/prepare_data.sh, egs/sms_wsj/CaCGMM/run.sh, egs/wham/ConvTasNet/run.sh, egs/wham/DPRNN/run.sh, egs/wham/DynamicMixing/run.sh, egs/wham/TwoStep/run.sh, egs/whamr/TasNet/run.sh, egs/wsj0-mix/DeepClustering/run.sh
Remove abs path from all the recipes
Next PR remove env creation from the recipes
=> Remove path

egs/dns_challenge/baseline/run.sh, egs/librimix/ConvTasNet/run.sh, egs/wham/ConvTasNet/run.sh, egs/wham/DPRNN/run.sh, egs/wham/DynamicMixing/run.sh, egs/wham/TwoStep/run.sh, egs/whamr/TasNet/run.sh, egs/wsj0-mix/DeepClustering/run.sh
Copy log files after training and evaluation, easier in this way.
=> Copy train and eval logs to expdir

asteroid/data/dns_dataset.py, asteroid/data/librimix_dataset.py, asteroid/data/musdb18_dataset.py, asteroid/data/wham_dataset.py, asteroid/data/whamr_dataset.py, asteroid/data/wsj0_mix.py
This'll be used to add metadata to model upload
=> [src] Add dataset_name attribute to all data.Dataset

asteroid/engine/system.py, requirements.txt, setup.py, tests/engine/system_test.py
Ended up running several tests with 0.6.0 against 0.7.6 and could reach the same perfs again. 
We still have the same perfs problem with pl 0.7.1 so we'll require higher that 0.7.3.
=> Upgrade pytorch-lightning to >= 0.7.3

asteroid/losses/pmsqe.py
torch.pow() gives NaN on backward pass if values are zero, to avoid it small positive number is added. Also, added device parameter to define this class on GPU
=> In PMSQE code, solved NAN issue raised by backward pass on torch.pow()

egs/dns_challenge/baseline/train.py, egs/librimix/ConvTasNet/train.py, egs/wham/ConvTasNet/train.py, egs/wham/DPRNN/train.py, egs/wham/DynamicMixing/train.py, egs/wham/FilterbankDesign/train.py, egs/wham/TwoStep/train.py, egs/whamr/TasNet/train.py
That's not useful, can be wrong sometimes + raises exception.
=> [egs] Remove shuffle=True in validation Loader (lightning error)

egs/dns_challenge/baseline/run.sh, egs/fuss/baseline/run.sh, egs/sms_wsj/CaCGMM/run.sh, egs/wham/ConvTasNet/run.sh, egs/wham/DPRNN/run.sh, egs/wham/DynamicMixing/run.sh, egs/wham/TwoStep/run.sh, egs/whamr/TasNet/run.sh, egs/wsj0-mix/DeepClustering/run.sh
```bash
find . -iname run.sh -exec sed -i '/set -e.*/ d' {} \;
find . -iname run.sh -exec sed -i '2iset -e  # Exit on error' {} \;
```
=> [egs] set -e in all recipes to exit or errors

asteroid/data/kinect_wsj.py, egs/kinect-wsj/DeepClustering/train.py, egs/kinect-wsj/README.md, egs/wsj0-mix/DeepClustering/model.py
Just added the README on the dataset, the Chime5 license, fixed an import in DeepClustering (my bad).
=> [src & egs] Add Kinect-WSJ licenses + small fixes

egs/librimix/ConvTasNet/eval.py, egs/librimix/ConvTasNet/run.sh, egs/librimix/ConvTasNet/train.py
Follow the example of wham/ConvTasNet and share on Librimix, pretrained models to come !
@JorisCos, can you review please?
=> [egs] Enable pretrained models sharing on LibriMix

egs/librimix/ConvTasNet/eval.py, egs/librimix/ConvTasNet/train.py, egs/wham/ConvTasNet/eval.py, egs/wham/DPRNN/eval.py, egs/wham/DynamicMixing/eval.py, egs/wham/TwoStep/eval.py, egs/whamr/TasNet/eval.py
This PR optimize imports in train and fixes some small issues in the eva script 
I added `get_metrics(..., metrics_list =compute_metrics)` in all eval scripts
=> Corrections on LibriMix eval and train and evals scripts 

asteroid/data/musdb18_dataset.py
The is to address the "issue" mentioned in #47.
We can add a `targets` argument to the dataset so that the return sources are in the form of a Tensor (with the required target sources stacked in the given order) instead of the dict.
```python
MUSDB18Dataset(root)
MUSDB18Dataset(root, sources=['vocals', 'bass', 'drums'])
MUSDB18Dataset(root, sources=['vocals', 'bass', 'drums'], targets=['vocals', 'drums'])
```
The main use case is that we don't have to subclass `System` to use it, which makes sense!
@faroit Could you review please and tell me if you'd be fine with that
@groadabike, would this suit your needs?
=> [src] Add targets argument to musdb18_dataset.py

asteroid/data/librimix_dataset.py
Instantiate LibriMix from download in one line. 
Needs review and basic testing but it works on my side.
=> [src] LibriMix from download

asteroid/masknn/recurrent.py, tests/masknn/recurrent_test.py
Finally got time to examine the output of bidir RNN.
@popcornell Could you review tell me if it makes sense for you? 
Thanks
=> [src & tests] Bidirectional residual RNN

egs/wham/ConvTasNet/eval.py
- based on PR #148 made by Mathieu for librimix :
https://github.com/mpariente/asteroid/pull/148/files
=> Fix clipping problems when saving estimate wav file for Wham ConvTasNet

asteroid/masknn/norms.py, egs/wham/DynamicMixing/local/augmented_wham.py, tests/masknn/norms_test.py
as noted by JusperLee in mpariente/asteroid#168. 
Added also checks to prevent clipping.
=> Dynamic Mixing fix 

asteroid/data/__init__.py, asteroid/data/sms_wsj_dataset.py, egs/dns_challenge/baseline/train.py, egs/kinect-wsj/DeepClustering/train.py, egs/librimix/ConvTasNet/train.py, egs/wham/ConvTasNet/train.py, egs/wham/DPRNN/train.py, egs/wham/DynamicMixing/train.py, egs/wham/TwoStep/train.py, egs/whamr/TasNet/train.py, egs/wsj0-mix/DeepClustering/train.py
This pull request adds a Dataset for the SMS_WSJ database. This is a first step in implementing a neural network based example.
=> adds Dataset for SmsWsj

.pre-commit-config.yaml, notebooks/01_AsteroidGettingStarted.ipynb, notebooks/02_Filterbank.ipynb, notebooks/03_PITLossWrapper.ipynb
For now, the pre-commit hook doesn't handle ipynb right so it might need to be disabled before committing. 
Just fixing some notebooks
=> [notebooks] Fix notebooks

.coveragerc, .github/workflows/test_asteroid_package.yml, hubconf.py
Everything is in the tittle ! 
In the rush of adding new supported models, we forgot to extend the hub, here it is !
=> [hub] Add LSTMTasNet/DPTNet/SuDORMRFNet to torch.hub!

asteroid/data/__init__.py, asteroid/data/fuss_dataset.py
=> [src] Add FUSS dataset from FUSS PR

asteroid/dsp/__init__.py, docs/source/index.rst, docs/source/package_reference/dsp.rst
Because these are cool functions
=> [docs] Add DSP section to docs

docs/source/package_reference/data.rst, docs/source/package_reference/masknn.rst, docs/source/package_reference/optimizers.rst, docs/source/supported_datasets.rst
Everything is in the description.
=> [docs] Add schedulers, activations docs and improve datasets' docs

asteroid/utils/test_utils.py, tests/engine/scheduler_test.py, tests/engine/system_test.py
Forgot to do that. 
It's also useful because it can serve as an example later (let's test mixed precision with the new code first).
Is it normal that the step is not incremented @popcornell ? 
[See here](https://github.com/mpariente/asteroid/blob/master/asteroid/engine/schedulers.py#L117)
=> [tests] Add scheduler tests

asteroid/engine/system.py, tests/engine/system_test.py
As pointed out by @jonashaag in #217 
Quite critical, because 0.3.1 was just released. We're lucky we have schedulers in all our recipes.
Tag @popcornell
=> [src & tests] Fix no scheduler bug 

asteroid/models/base_models.py, asteroid/scripts/asteroid_cli.py, tests/models/models_test.py
This refactors the method, adds two argument to the CLI to force overrite or change the output directory, but, I'd like feedback on two things 
- Rescaling to input waveform
- Only handling single channel files (and not combining channels in any way)
What do you think about that ?
=> [CLI] Refactore `separate` method 

egs/demask/run.sh, egs/demask/train.py
Last minute change, Samu, can you review?
=> [egs] Fix declared unused variables in DeMask

asteroid/engine/system.py
As pointed out by @jonashaag 
This is quite critical, but luckily, all out recipes have a LR scheduler.
=> [src] Fix uncalled optimizer in System without LR schedule

docs/source/faq.rst
This is the second time the question is asked. Time to put it in the FAQ (if anyone reads it haha)
=> [docs] Add issue #250 to FAQ

CONTRIBUTING.md, asteroid/dsp/overlap_add.py, asteroid/models/base_models.py, asteroid/models/conv_tasnet.py, asteroid/models/dprnn_tasnet.py, asteroid/models/dptnet.py, asteroid/models/lstm_tasnet.py, asteroid/models/sudormrf.py, asteroid/utils/generic_utils.py, tests/models/models_test.py, tests/utils/utils_test.py
=> Split base model

.pre-commit-config.yaml, asteroid/data/avspeech_dataset.py, asteroid/filterbanks/multiphase_gammatone_fb.py, asteroid/masknn/convolutional.py, asteroid/models/publisher.py, asteroid/utils/hub_utils.py, egs/avspeech/looking-to-listen/eval.py, egs/avspeech/looking-to-listen/local/loader/audio_mixer_generator.py, egs/avspeech/looking-to-listen/local/loader/download.py, egs/avspeech/looking-to-listen/model.py, egs/avspeech/looking-to-listen/train.py, egs/musdb18/OpenUnmix/test_dataloader.py, setup.py
#265 was formatted with black 19 🤦
=> Fix black 20.8b1 update

asteroid/models/conv_tasnet.py, asteroid/models/dccrnet.py, asteroid/models/dcunet.py, asteroid/models/demask.py, asteroid/models/dprnn_tasnet.py, asteroid/models/dptnet.py, asteroid/models/lstm_tasnet.py, asteroid/models/sudormrf.py
Add samplerate argument to all models and pass it to the filterbank. This should work as is. 
Ref: #274 #283
=> [src] Add sample_rate argument to all supported models.

asteroid/models/base_models.py, asteroid/scripts/asteroid_cli.py, tests/models/models_test.py
Use the sample rate property to automatically resample input wav files. 
Two questions: 
- Should the output be resampled at the original sample rate? 
- Should we use `librosa` or `torchaudio`? Librosa has more deps and is longer to load.. 
Ref #274
=> [src] Automatic resampling in separate.

asteroid/masknn/convolutional.py
Thanks to @yangyan008001 for reporting.
=> Fix #300: skip connection on good device

asteroid/losses/mse.py, asteroid/losses/sdr.py, tests/losses/loss_functions_test.py
We can also add this to more losses.
=> Add more shape checks to SDR and MSE losses

asteroid/models/dcunet.py
Another step towards removing the old hooks.
Ref #307
=> DCUNet: Replace old hooks by new one

docs/source/why_use_asteroid.rst, egs/dns_challenge/README.md
+ DNS citation didn't render well
=> [docs] New section in "Why asteroid?"

asteroid/__init__.py, tests/models/models_test.py
Will be useful for tests on them.
=> asteroid.show_available_models

docs/source/package_reference/data.rst, docs/source/readmes/dampvsep_README.md, docs/source/supported_datasets.rst, egs/dampvsep/ConvTasNet/README.md, egs/dampvsep/README.md
Thanks to @groadabike, we support separation on DAMP-VSEP, this PR adds it in the docs. 
Follow-up of #222
=> [docs] DAMP-VSEP in the docs !

asteroid/engine/schedulers.py, asteroid/engine/system.py, egs/wham/DPTNet/train.py, tests/engine/scheduler_test.py
Should fix https://github.com/mpariente/asteroid/issues/322. 
The changes are minimal.
=> schedulers not saved when they are dict 

asteroid/filterbanks/enc_dec.py
=> improve: improve Filterbank.forward error message

egs/wham/DPTNet/eval.py
=> Replace DPRNNTasNet with DPTNet

asteroid/filterbanks/transforms.py, tests/filterbanks/transforms_test.py
This PR adds
- Delta and double Delta computation of torch tensors
- A common phase correction that can be useful. 
Should we add `instantaneous_frequency` and `group_delay` functions? How about `nn.Module`? All the transforms are functional but having them as module can be useful.
=> [src] New phase features and transforms

asteroid/filterbanks/griffin_lim.py, asteroid/filterbanks/melgram_fb.py, asteroid/filterbanks/transforms.py, asteroid/losses/multi_scale_spectral.py, asteroid/losses/pmsqe.py, asteroid/models/demask.py, asteroid/utils/deprecation_utils.py, egs/dns_challenge/baseline/model.py, egs/kinect-wsj/DeepClustering/train.py, egs/wsj0-mix/DeepClustering/model.py, egs/wsj0-mix/DeepClustering/train.py, tests/filterbanks/stft_test.py, tests/filterbanks/transforms_test.py, tests/losses/loss_functions_test.py
As announced in #335 
I didn't add a version, but I guess it'll be the release after the next.
=> Better names in asteroid.filterbanks.transforms

asteroid/losses/__init__.py, asteroid/losses/mse.py, asteroid/losses/sdr.py
Remove all the losses which were supposed to be removed in asteroid v0.2.0 (a while ago :smile: )
=> [src] Remove deprecated losses

asteroid/masknn/recurrent.py, pyproject.toml, tests/engine/__init__.py, tests/filterbanks/transforms_test.py, tests/jit/__init__.py, tests/jit/jit_models_test.py, tests/losses/__init__.py, tests/models/demask_test.py, tests/models/models_test.py
I find myself scrolling on the little CI window of github actions to find the error again and it's very annoying. 
Example in #350 
I figured, let's catch the warnings we expect !
=> [CI] Catch warnings we expect

.github/workflows/test_asteroid_package.yml, tests/filterbanks/filterbanks_test.py
Ugly, but simple (if it works).
I'd be ok with that for now.
=> [CI] Build with torch-nightly 

asteroid/dsp/deltas.py, asteroid/dsp/vad.py, asteroid/filterbanks/transforms.py, egs/kinect-wsj/DeepClustering/train.py, egs/wsj0-mix/DeepClustering/model.py, egs/wsj0-mix/DeepClustering/train.py, tests/dsp/deltas_tests.py, tests/dsp/vad_test.py
Migrate back from asteroid-filterbanks because it's unrelated to filterbanks or complex-like tensors.
=> [src] Add ebased_vad and deltas

docs/source/conf.py
Best use of my time for a long time !! I'm soo happy about this :star_struck: 
Basically, the "Source" button used to bring us to a local page containing the source code (uneditable, lines with anchor etc..), now it brings us on the definition ON GITHUB!
It even follows `asteroid-filterbanks` :heart_eyes: 
I'm in love haha 
@michelolzam : actually got it to work :wink: 
Refs: [Lasagne#262](https://github.com/Lasagne/Lasagne/pull/262) and [Lasagne#290](https://github.com/Lasagne/Lasagne/pull/290)
=> [docs] Links to GitHub code from the docs :tada:

CONTRIBUTING.md, README.md, docs/README.md, docs/source/conf.py, egs/README.md, notebooks/00_GettingStarted.ipynb, notebooks/01_APIOverview.ipynb, setup.py
Rename badges and references to point to the new repo.
=> [docs] Migrate to asteroid-team

asteroid/masknn/attention.py
Should fix https://github.com/asteroid-team/asteroid/issues/380.
=> bug in attention.py due to mha input shape

.github/workflows/test_model_consistency.yml
Just checking if both timed tests and manual trigger work.
=> [ci] Layout for model consistency tests

asteroid/utils/hub_utils.py, tests/utils/hub_utils_test.py
Thanks to @julien-c for the tag filter!
=> [hub] Use API filter for faster model list

setup.py
As requested here: https://github.com/asteroid-team/asteroid-filterbanks/pull/5#issuecomment-742619257
=> Deduplicate version number

egs/dampvsep/ConvTasNet/train.py, egs/librimix/ConvTasNet/train.py, egs/wham/ConvTasNet/train.py, egs/wham/DPRNN/train.py, egs/wham/DPTNet/train.py, egs/wham/MixIT/train.py
=> [egs] Pass samplerate to models 

.github/workflows/lint.yml, asteroid/engine/__init__.py
Try to set it up again. 
Inspired by how it works in this project: https://github.com/UnityTechnologies/open-project-1
=> Setup automatic linter

asteroid/models/fasnet.py, egs/TAC/local/conf.yml, egs/TAC/run.sh
=> fixed bug about reshaping

asteroid/utils/hub_utils.py, requirements/torchhub.txt, setup.py
References: https://github.com/asteroid-team/asteroid/pull/409
Also references: https://github.com/huggingface/huggingface_hub/pull/8
Cheers!
=> Upgrade to huggingface_hub >= 0.0.2

.readthedocs.yml, docs/README.md
Builds are failing for a while. 
I suspect it's the refactoring of requirements which is the source of it.
=> [docs] Fix RTD build

asteroid/masknn/_dcunet_architectures.py
Should fix the build with nightly [here](https://github.com/asteroid-team/asteroid/runs/2191057550).
=> Fix padding in DCUNet ConvTranspose2d

asteroid/masknn/convolutional.py, asteroid/models/conv_tasnet.py, tests/masknn/convolutional_test.py
This PR adds causality to ConvTasNet. It is inspired by https://github.com/locuslab/TCN .
=> Causal ConvTasNet

notebooks/00_GettingStarted.ipynb
=> fix a bug in 00_GettingStarted.ipynb

asteroid/dsp/beamforming.py, tests/dsp/beamforming_test.py
- Integrate a stabilized Cholesky decomposition in the GEV beamformer
- Externalize the function to compute the beamforming vector
=> Stabilize GEV beamformer

asteroid/dsp/beamforming.py, tests/dsp/beamforming_test.py
Based on a posteriori SNR from [here](https://www.merl.com/publications/docs/TR2016-072.pdf) 
Still need to enable custom channel selection with integer and torch.Tensor
=> [src] Beamforming: optimal channel selection

asteroid/engine/system.py, requirements/install.txt, setup.py
This doesn't break anything. 
And then, 0.5.1 release.
=> [src] Lift the ligthning<1.3.0 restriction

asteroid/dsp/beamforming.py
See [issue # 518](https://github.com/asteroid-team/asteroid/issues/518).
=> Preverve complex eigen values in generalized_eigenvalue_decomposition()

README.md, egs/musdb18/X-UMX/README.md, egs/musdb18/X-UMX/local/dataloader.py, egs/musdb18/X-UMX/requirements.txt, egs/musdb18/X-UMX/train.py
Summary:
- `./README.md`: added X-UMX to the lists `Available recipes`
- `egs/musdb18/X-UMX/train.py`: replaced `args` in a class with appropriate inputs
- `egs/musdb18/X-UMX/README.md`: added information regarding related projects
- `egs/musdb18/X-UMX/local/dataloader`: fixed bug
=> Fixed bug and README.md regarding X-UMX

asteroid/dsp/beamforming.py, tests/dsp/beamforming_test.py
GEVD beamformer is a kind of SDW MWF but computed in eigen space. It gives a good SIR but with less distortion than GEV beamformer.
The code is based on the one written by @nfurnon.
=> Add GEVD beamformer

asteroid/utils/hub_utils.py
This will enable Asteroid-specific download stats.
FYI @julien-c
=> Add library version and name for Hugging Face download stats

asteroid/models/__init__.py
I found a mistake while trying to use FasNetTAC with pretrained model (https://huggingface.co/popcornell/FasNetTAC-paper).
This simple fix works for me.
=> Fix loading FasNetTAC model

asteroid/models/sudormrf.py
Fix #598 . `padding` device wasn't set which caused errors when training on gpus
=> Fix device in padding for sudormrf  #598  

asteroid/engine/schedulers.py, asteroid/engine/system.py, egs/LibriVAD/train.py, egs/TAC/train.py, egs/dampvsep/ConvTasNet/train.py, egs/demask/train.py, egs/dns_challenge/baseline/train.py, egs/kinect-wsj/DeepClustering/train.py, egs/librimix/ConvTasNet/train.py, egs/librimix/DCCRNet/train.py, egs/librimix/DCUNet/train.py, egs/librimix/DPRNNTasNet/train.py, egs/librimix/DPTNet/train.py, egs/librimix/SuDORMRFImprovedNet/train.py, egs/librimix/SuDORMRFNet/train.py, egs/musdb18/X-UMX/train.py, egs/wham/ConvTasNet/train.py, egs/wham/DPRNN/train.py, egs/wham/DPTNet/train.py, egs/wham/DynamicMixing/train.py, egs/wham/FilterbankDesign/train.py, egs/wham/MixIT/train.py, egs/wham/TwoStep/train.py, egs/whamr/TasNet/train.py, egs/wsj0-mix-var/Multi-Decoder-DPRNN/train.py, egs/wsj0-mix/DeepClustering/train.py, requirements/install.txt, setup.py, tests/engine/system_test.py, tests/losses/sinkpit_wrapper_test.py
After months of being late, we should upgrade. 
For the recipes, we need to use the `accelerator`, `strategy` and `devices` arguments instead of `distributed_backend` and `gpus`.
=> [src&egs] Upgrade to PL 1.5.0+

asteroid/dsp/beamforming.py
Available (at least) from 1.8.0 and deprecated in the nightly builds already.
=> Use torch.linalg for solve and cholesky

egs/librimix/ConvTasNet/run.sh, egs/librimix/DCCRNet/run.sh, egs/librimix/DCUNet/run.sh, egs/librimix/DPRNNTasNet/run.sh, egs/librimix/DPTNet/run.sh, egs/librimix/SuDORMRFImprovedNet/run.sh, egs/librimix/SuDORMRFNet/run.sh
=> [egs] Raise error if storage_dir not specified in LibriMix recipes

asteroid/masknn/norms.py
Fixes computation of variance in cumulative normalization (#648).
=> Fix cumulative normalization
